### ISSUE TITLE
Are you open to accept PRs?

### ISSUE THREAD

**Issue by oldravian** [highsidelabs/walmart-api-php#7]
Today, I used this package. It's very well-written and well-documented. However, I faced some errors in the code and I manually fixed that by updating your classes. I wanted to make a PR so that you can check the issue and my fixes. I'm opening this thread because I didn't find any contribution guide here.

**Comment by jlevers** [comment]
Yep, definitely open to PRs! The one thing to be aware of is that (almost) all the classes are autogenerated based on OpenAPI models, which you can find in the `resources/schemas/` folder, so changing individual classes isn't a long-term solution. There are two ways to make enduring fixes:
1. Change the generation process to make it so that different files are produced, or existing files are produced differently
2. Make schema corrections to one-off issues in the Walmart OpenAPI schemas by modifying `resources/schema-corrections.json`

If you need more details, let me know – I'll write a proper contributing guide at some point, but I haven't gotten around to it yet.
